[package]
name = "rscast"
version = "0.1.0"
authors = ["jn9159 <jn9159@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
sdl2 = "0.33.0"